# depend-on:
# * bigdata/confluent
# * database/elastic
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB: datahub
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/database-init.sql:/docker-entrypoint-initdb.d/initdb.sql

  datahub-gms:
    image: linkedin/datahub-gms:v0.9.6.1
    env_file:
      - ./etc/datahub.env
      - ./etc/datahub-gms.env
    depends_on:
      - postgres

  # account: datahub/datahub
  datahub-frontend:
    image: linkedin/datahub-frontend-react:v0.9.6.1
    env_file:
      - ./etc/datahub.env
      - ./etc/datahub-frontend.env
    ports:
      - 9002:9002
    depends_on:
      - datahub-gms

  datahub-actions:
    # image: acryldata/datahub-actions:v0.0.10
    image: hub.teko.vn/dataops/datahub/actions:0.0.10
    env_file:
      - ./etc/datahub.env
      - ./etc/datahub-actions.env
    depends_on:
      - datahub-gms

volumes:
  postgres_data:

networks:
  default:
    name: bookshelf

## References:
# * Kafka Topic:
#     https://github.com/datahub-project/datahub/blob/master/docs/deploy/confluent-cloud.md
#     https://github.com/datahub-project/datahub/blob/master/metadata-events/mxe-registration/src/main/java/com/linkedin/mxe/Topics.java
#     https://github.com/datahub-project/datahub/blob/master/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/TopicConventionFactory.java
