# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 8069, host: 8069

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    # Install PostgreSQL
    apt-get install -y postgresql

    # Install Node.js
    curl -sL https://deb.nodesource.com/setup_10.x | bash -
    apt-get install -y nodejs

    # Install Python3
    apt-get install -y python3 python3-pip

    # Install other dependences
    npm install -g rtlcss
    pip3 install num2words xlwt
    if ! dpkg -s wkhtmltox >/dev/null 2>&1; then
      wkhtmltox_version=0.12.5
      curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/${wkhtmltox_version}/wkhtmltox_${wkhtmltox_version}-1.$(lsb_release -cs)_amd64.deb
      dpkg -i --force-depends wkhtmltox.deb
      apt-get install -y -f --no-install-recommends
      rm -rf wkhtmltox.deb
    fi

    # Install Odoo
    wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
    echo "deb http://nightly.odoo.com/12.0/nightly/deb/ ./" > /etc/apt/sources.list.d/odoo.list
    apt-get update
    apt-get install -y odoo
  SHELL
end
