# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    APACHE_DIST=https://apache.org/dist
    APACHE_MIRROR=http://mirrors.viethosting.com/apache

    apt update
    apt install -y openjdk-8-jdk
    ln -sf /usr/bin/python3   /usr/bin/python
    cp /vagrant/init.sh       /etc/profile.d/
    source /etc/profile.d/init.sh

    cd /opt
    if [ ! -d "${SPARK_HOME}" ]; then
      curl -LO "${APACHE_MIRROR}/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz";
      tar -xzf "spark-${SPARK_VERSION}-bin-hadoop2.7.tgz" --owner root --group root --no-same-owner;
      rm  -rf  "spark-${SPARK_VERSION}-bin-hadoop2.7.tgz"
      mv       "spark-${SPARK_VERSION}-bin-hadoop2.7" spark;
    fi
  SHELL
end
