server:
  http_listen_port: 3200
  grpc_listen_port: 9095

storage:
  trace:
    backend: local
    local:
      path: /var/lib/tempo/blocks
    wal:
      path: /var/lib/tempo/wal

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        grpc:
        thrift_http:
        thrift_binary:
        thrift_compact:
    zipkin:
    opencensus:
