logs:
  configs:
  - name: default
    clients:
    - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /var/lib/agent/positions.yaml
    scrape_configs:
    - job_name: system
      static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*log

metrics:
  global:
    scrape_interval: 60s
    remote_write:
    - url: http://prometheus:9090/api/v1/write
  configs:
  - name: default
    scrape_configs:
    - job_name: avalanche
      static_configs:
      - targets: [avalanche:9001]
