logs:
  configs:
  - name: default
    clients:
    - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /var/lib/agent/positions.yaml
    scrape_configs:
    - job_name: system
      static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*log
