services:
  grafana:
    image: grafana/grafana:12.0.1
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: SuperSecr3t
    ports:
      - 3001:3000
    volumes:
      - ./configs:/etc/grafana
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  default:
    name: bookshelf
