services:
  grafana:
    image: grafana/grafana:11.5.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: SuperSecr3t
      # GF_INSTALL_PLUGINS: grafana-oncall-app
    ports:
      - 3001:3000
    volumes:
      - ./configs:/etc/grafana
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  default:
    name: bookshelf
