version: '3.7'

services:
  grafana:
    image: grafana/grafana:9.2.1
    ports:
    - 3000:3000
    volumes:
    - ./configs:/etc/grafana
    - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  default:
    name: bookshelf
    external: true
