services:
  minio:
    image: minio/minio
    command: [server, --address=:9000, --console-address=:9001, /data]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - minio_data:/data

  # mc:
  #   image: minio/mc
  #   entrypoint: [/bin/sh]
  #   tty: true
  #   environment:
  #     MC_HOST_local: http://admin:SuperSecr3t@minio:9000
  #   volumes:
  #   - .:/workspace

volumes:
  minio_data:

networks:
  default:
    name: bookshelf
