# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  (0..2).each do |i|
    pri = (i == 0)
    config.vm.define "minio-#{i}", primary: pri do |minio|
      minio.vm.hostname = "minio-#{i}"

      minio.vm.network "private_network",
        ip: "192.168.50.#{100 + i}",
        virtualbox__intnet: true
      minio.vm.network "forwarded_port",
        guest: 9000,
        host:  9000 + i, host_ip: "127.0.0.1"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -f /usr/local/bin/minio ]; then
      curl https://dl.minio.io/server/minio/release/linux-amd64/minio -o /usr/local/bin/minio
      chmod +x /usr/local/bin/minio
    fi
    if [ ! -f /usr/local/bin/mc ]; then
      curl https://dl.minio.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
      chmod +x /usr/local/bin/mc
    fi
    if [ ! -d  /var/lib/minio ]; then
      mkdir -p /var/lib/minio
      chown -R vagrant:vagrant /var/lib/minio
    fi
  SHELL
end

# ===== REQUIREMENTS =====
# min: 2 disks/node
# ========================
# export MINIO_ACCESS_KEY=admin
# export MINIO_SECRET_KEY=Teko@123?
# minio server /var/lib/minio
# minio server http://192.168.50.10{0...2}/var/lib/minio/disk{1...4}
