# -*- mode: ruby -*-
# vi: set ft=ruby :

num_instances=3

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  (1..num_instances).each do |i|
    vm_name = (i == 1) ? "kmaster" : ("kworker-%02d" % [i-1])

    config.vm.define vm_name do |host|
      host.vm.hostname = vm_name
      host.vm.network :private_network, ip: "172.18.18.#{i+100}"
    end

    config.vm.provision "shell", inline: <<-SHELL
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

      apt update
      apt install -y kubelet kubeadm kubectl containerd.io
    SHELL

    config.vm.provision "file", source: "crictl.yaml", destination: "/etc/crictl.yaml"
    config.vm.provision "file", source: "modules.conf", destination: "/etc/modules-load.d/modules.conf"
    config.vm.provision "file", source: "99-kubernetes-cri.conf", destination: "/etc/sysctl.d/99-kubernetes-cri.conf"
  end
end
