version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB:       airflow
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: SuperSecr3t
    ports:
    - 15672:15672
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq

  airflow-webserver:
    image: hub.teko.vn/data/airflow:1.10.7-all
    command: [webserver]
    ports:
    - 8080:8080
    volumes:
    - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    - ./dags:/opt/airflow/dags

  airflow-scheduler:
    image: hub.teko.vn/data/airflow:1.10.7-all
    command: [scheduler]
    volumes:
    - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    - ./dags:/opt/airflow/dags

  airflow-worker:
    image: hub.teko.vn/data/airflow:1.10.7-all
    command: [worker]
    volumes:
    - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    - ./dags:/opt/airflow/dags

volumes:
  postgres_data:
  rabbitmq_data:
