version: "3.7"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB:       airflow
    # ports:
    # - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    # ports:
    # - 6379:6379

  airflow:
    image: hub.teko.vn/dataops/airflow:2.4-b1
    command: [standalone]
    ports:
    - 8080:8080
    volumes:
    - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    - ./dags:/opt/airflow/dags

volumes:
  postgres_data:

networks:
  default:
    name: bookshelf
    external: true

######### REFERENCES #########
# $ airflow users create --username admin \
#     --firstname FIRST_NAME --lastname LAST_NAME \
#     --role Admin --email admin@example.org
