# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y php-fpm nginx

    cp /vagrant/files/nginx.conf /etc/nginx/sites-available/default
    cp /vagrant/files/info.php   /var/www/html/info.php
    sed -i '/pm.status_path/c\pm.status_path = \/status' /etc/php/7.0/fpm/pool.d/www.conf

    service php7.0-fpm restart
    service nginx restart
  SHELL
end
