apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id
          matcherType: label
          name: TraceID
          url: $${__value.raw}
          urlDisplayLabel: View Trace
        - datasourceUid: tempo
          matcherRegex: span_id
          matcherType: label
          name: SpanID
          url: |-
            { span:id="$${__value.raw}" }
          urlDisplayLabel: View Span
