apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Mimir
      prometheusVersion: 2.9.1 # > 2.9.x
      cacheLevel: High
      incrementalQuerying: true
