apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: mimir
        tags:
          - key: service.name
            value: server
        queries:
          - name: Request rate
            query: |-
              sum by(client, server)(rate(traces_service_graph_request_total{$$__tags}[$$__rate_interval]))
          - name: Error rate
            query: |-
              sum by(client, server)(rate(traces_service_graph_request_errors_total{$$__tags}[$$__rate_interval]))
