# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network :private_network, ip: "172.18.18.100"

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y ipvsadm
    curl -sSL get.docker.io | bash
    usermod -aG docker vagrant

    if ! command -v docker-compose >/dev/null 2>&1; then
      curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    fi
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant/backends
    docker-compose up -d
  SHELL
end
