version: "3.7"

services:
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.6.0
    environment:
      OPENSEARCH_HOSTS: http://opensearch:9200
    ports:
      - 5601:5601

volumes:
  opensearch_data:

networks:
  default:
    name: bookshelf

# https://opensearch.org/docs/latest/install-and-configure/install-opensearch/plugins/
# https://opensearch.org/docs/latest/install-and-configure/install-dashboards/plugins/
# https://opensearch.org/docs/latest/security-plugin/index/
