# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 15672, host: 15672

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y rabbitmq-server
    rabbitmq-plugins enable rabbitmq_management
  SHELL
end
