version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
    - discovery.type=single-node
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    # environment:
    #   SERVER_NAME: kibana
    #   ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
    - 5601:5601

volumes:
  elasticsearch:

networks:
  default:
    external:
      name: bookshelf
