version: "3.7"

services:
  mimir:
    image: grafana/mimir:2.5.0
    command:
    - -config.file=/etc/mimir/config.yaml
    ports:
    - 9009:9009
    volumes:
    - ./configs:/etc/mimir
    - mimir_data:/var/lib/mimir

volumes:
  mimir_data:

networks:
  default:
    name: bookshelf
    external: true


##### References #####
# * https://grafana.com/docs/mimir/latest/operators-guide/configure/reference-configuration-parameters/
# * https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/
# * https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/
