version: '3.7'

services:
  hdfs-namenode:
    image: hub.teko.vn/dataops/hadoop:3.3.1
    command: [/usr/local/scripts/hadoop-start.sh, namenode]
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 9870:9870
    volumes:
    - ./datasets/:/datasets/
    - ./scripts/:/usr/local/scripts/
    - ./configs/:/opt/hadoop/etc/hadoop:ro
    - namenode_data:/var/lib/hadoop

  hdfs-datanode1:
    image: hub.teko.vn/dataops/hadoop:3.3.1
    command: [/usr/local/scripts/hadoop-start.sh, datanode]
    depends_on:
    - hdfs-namenode
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
    - ./scripts/:/usr/local/scripts/
    - ./configs/:/opt/hadoop/etc/hadoop:ro
    - namenode_data:/var/lib/hadoop

volumes:
  namenode_data:
  datanode1_data:

networks:
  default:
    name: bookshelf
