version: "3.7"

services:
  ##### PostgreSQL #####
  # https://hub.docker.com/_/postgres
  # Help:
  # > psql -U postgres [-W]
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    ports:
    - 5432:5432
    volumes:
    - ./sample/:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  # > psql -U postgres -p 6432 [pgbouncer]
  pgbouncer:
    image: bitnami/pgbouncer:1.18.0
    profiles: [pgbouncer]
    ports:
    - 6432:6432
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: SuperSecr3t
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_AUTH_USER: postgres
    depends_on:
    - postgres

volumes:
  postgres_data:

networks:
  default:
    name: bookshelf
    external: true
