# -*- mode: ruby -*-
# vi: set ft=ruby :

SHELL = "bash" # options: bash, fish, zsh

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", path: "./scripts/bash-debian.install"  if SHELL == "bash"
  config.vm.provision "shell", path: "./scripts/fish-debian.install"  if SHELL == "fish"
  config.vm.provision "shell", path: "./scripts/zsh-debian.install"   if SHELL == "zsh"
end
