services:
  cube:
    image: cubejs/cube:v0.33
    environment:
      CUBEJS_DEV_MODE: true # https://cube.dev/docs/configuration/overview#development-mode
      CUBEJS_API_SECRET: SuperSecr3t
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: demo-db.cube.dev
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: ecom
      CUBEJS_DB_USER: cube
      CUBEJS_DB_PASS: 12345
    ports:
      - 4000:4000   # WebUI
      - 15432:15432 # PostgreSQL
    volumes:
      - ./conf:/cube/conf

networks:
  default:
    name: bookshelf
