# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  (0..2).each do |i|
    pri = (i == 0)
    config.vm.define "etcd-#{i}", primary: pri do |minio|
      minio.vm.hostname = "etcd-#{i}"

      minio.vm.network "private_network",
        ip: "192.168.50.#{100 + i}",
        virtualbox__intnet: true
      minio.vm.network "forwarded_port",
        guest: 2379,
        host:  2379 + i, host_ip: "127.0.0.1"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y etcd
  SHELL
end

# alias etcdctl='ETCDCTL_API=3 etcdctl --endpoints=http://192.168.50.100:2379,http://192.168.50.101:2379,http://192.168.50.102:2379'
