# -*- mode: ruby -*-
# vi: set ft=ruby :

golang_version = "1.11"
golang_artifact = "go#{golang_version}.linux-amd64.tar.gz"
golang_download_url = "https://dl.google.com/go/#{golang_artifact}"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # https://medium.com/better-programming/install-go-1-11-on-ubuntu-18-04-16-04-lts-8c098c503c5f
  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -d /usr/local/go ]; then
      wget #{golang_download_url}
      tar -xzvf #{golang_artifact} -C /usr/local
      rm -rf #{golang_download_url}
    fi

    if [ ! -d ~vagrant/go ]; then
      mkdir -p ~vagrant/go
      chown vagrant:vagrant ~vagrant/go
    fi

    if [ ! -f /etc/profile.d/golang.sh ]; then
      cp /vagrant/configs/golang.sh /etc/profile.d/golang.sh
    fi
  SHELL
end
