version: '2'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: SuperSecr3t
    volumes:
    - mariadb_data:/var/lib/mysql

  orangehrm:
    image: orangehrm/orangehrm:5.4
    environment:
      ORANGEHRM_DATABASE_HOST: mariadb
      ORANGEHRM_DATABASE_USER: root
      ORANGEHRM_DATABASE_PASSWORD: SuperSecr3t
      ORANGEHRM_DATABASE_NAME: orangehrm
    ports:
    - 8200:80
    - 8443:443
    volumes:
    - orangehrm_data:/orangehrm
    depends_on:
    - mariadb

volumes:
  mariadb_data:
  orangehrm_data:

networks:
  default:
    name: bookshelf
    external: true
