# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.hostname = "iam.kites.rocks"

  config.vm.provision "shell", inline: <<-SHELL
    dnf module install -y idm:DL1
    # dnf install -y @idm:DL1

    dnf install -y freeipa-server
    dnf install -y ipa-server-dns

    # ipa-server-install
    # ref: https://computingforgeeks.com/how-to-install-and-configure-freeipa-server-on-rhel-centos-8/
  SHELL

  # Ports:
  #   TCP Ports:
  #     * 80, 443: HTTP/HTTPS
  #     * 389, 636: LDAP/LDAPS
  #     * 88, 464: kerberos
  #   UDP Ports:
  #     * 88, 464: kerberos
  #     * 123: ntp
end
