target: all
multitenancy_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9009
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_format: logfmt
  log_level: info

api:
  prometheus_http_prefix: /prometheus
  alertmanager_http_prefix: /alertmanager

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /mimir_data

blocks_storage:
  storage_prefix: blocks
  bucket_store:
    sync_dir: /mimir_local/tsdb-sync
  tsdb:
    dir: /mimir_local/tsdb
    wal_compression_enabled: true

ingester:
  ring:
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

ruler:
  rule_path: /mimir_local/rules

ruler_storage:
  storage_prefix: rules

alertmanager:
  data_dir: /mimir_local/alerts
  fallback_config_file: /etc/mimir/alertmanager-fallback.yaml

alertmanager_storage:
  storage_prefix: alerts

compactor:
  data_dir: /mimir_local/compactor
