version: "3.7"

services:
  ##### MySQL #####
  # https://hub.docker.com/_/mysql
  # Help:
  # > mysql -u root -p
  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ./sample/mysql/:/docker-entrypoint-initdb.d/
    - mysql_data:/var/lib/mysql

  ##### PostgreSQL #####
  # https://hub.docker.com/_/postgres
  # Help:
  # > psql -U postgres [-W]
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    ports:
    - 5432:5432
    volumes:
    - ./sample/postgres/:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  ##### Microsoft SQL Server #####
  # https://hub.docker.com/_/microsoft-mssql-server
  # https://docs.microsoft.com/sql/linux/sql-server-linux-configure-environment-variables
  # Help:
  # > /opt/mssql-tools/bin/sqlcmd -?
  # > /opt/mssql-tools/bin/sqlcmd -U sa [-P <pass>]
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SuperSecr3t
    ports:
    - 1433:1433
    volumes:
    - ./sample/mssql/:/docker-entrypoint-initdb.d/
    # - mssql_data:/var/opt/mssql/data

  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 27017:27017
    volumes:
    - ./sample/mongo/:/docker-entrypoint-initdb.d/
    - mongo_data:/data/db

  clickhouse:
    image: yandex/clickhouse-server:20.1
    ports:
    - 8123:8123  # HTTP interface
    - 9000:9000  # native TCP interface
    volumes:
    - ./sample/clickhouse/:/docker-entrypoint-initdb.d/
    - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile: 262144

  neo4j:
    image: neo4j:4.2
    environment:
      # default neo4j/neo4j
      NEO4J_AUTH: none # disable authentication
    ports:
    # https://neo4j.com/docs/operations-manual/current/configuration/ports/
    - 7474:7474 # HTTP
    - 7687:7687 # Bolt

volumes:
  mysql_data:
  postgres_data:
  # mssql_data:
  mongo_data:
  clickhouse_data:

networks:
  default:
    external:
      name: bookshelf
