# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 5601, host: 5601

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl apt-transport-https

    curl -sSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list

    apt-get update
    apt-get install -y elasticsearch kibana
  SHELL
end

# ElasticSearch
# xpack.security.enabled: true
# discovery.type: single-node
# bin/elasticsearch-setup-passwords interactive

# Kibana
# elasticsearch.username: "kiibana"
# elasticsearch.password: "-------------------------"
