version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB:       metastore
    # ports:
    # - 5432:5432
    volumes:
    - ../../database/postgres/sample:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: hub.teko.vn/dataops/hive:3.1.3
    # HOTFIX: Illegal character in hostname at index 13: thrift://hive_hive-metastore_1.bookshelf:9083
    # Caused at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.resolveUris(HiveMetaStoreClient.java:267)
    container_name: hive-metastore
    entrypoint: ["/usr/local/scripts/metastore-entrypoint.sh"]
    depends_on:
    - postgres
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 9083:9083
    volumes:
    - ./scripts/:/usr/local/scripts/
    - ./configs/hive/:/opt/hive/conf/
    - ./configs/hadoop/:/opt/hadoop/etc/hadoop/

  hive-server2:
    image: hub.teko.vn/dataops/hive:3.1.3
    entrypoint: ["/usr/local/scripts/hiveserver2-entrypoint.sh"]
    depends_on:
    - hive-metastore
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 10000:10000
    - 10002:10002 # WebUI
    volumes:
    - ./scripts/:/usr/local/scripts/
    - ./configs/hive/:/opt/hive/conf/
    - ./configs/hadoop/:/opt/hadoop/etc/hadoop/

  beeline:
    image: hub.teko.vn/dataops/hive:3.1.3
    entrypoint: ["/bin/bash"]
    tty: true
    profiles: [cli]

volumes:
  postgres_data:

networks:
  default:
    name: bookshelf
