version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB:       metastore
    ports:
    - 5432:5432
    volumes:
    - ../../database/sample/postgres:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: hub.teko.vn/data/hive:3.1.2-hadoop-3.1.0
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: [hive, --service, metastore, --verbose]
    volumes:
    - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    - ../configs/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    - ../configs/hive/hive-site.xml:/opt/hive/conf/hive-site.xml

  hive-server2:
    image: hub.teko.vn/data/hive:3.1.2-hadoop-3.1.0
    # command: sleep 3600 # schematool -dbType postgres -initSchema
    command: [hive, --service, metastore, --verbose]
    volumes:
    - ../configs/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    - ../configs/hive/hive-site.xml:/opt/hive/conf/hive-site.xml

volumes:
  postgres_data:

networks:
  default:
    external:
      name: bookshelf
