version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
      POSTGRES_DB:       metastore
    ports:
    - 5432:5432
    volumes:
    - ../../database/sample/postgres:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: hub.teko.vn/data/hive:3.1.2-hadoop-3.1.0
    # HOTFIX: Illegal character in hostname at index 13: thrift://hive_hive-metastore_1.bookshelf:9083
    # Caused at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.resolveUris(HiveMetaStoreClient.java:267)
    container_name: hive-metastore
    entrypoint: ["/usr/local/scripts/metastore-entrypoint.sh"]
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
    - ./scripts/:/usr/local/scripts/
    - ../configs/hive/:/opt/hive/conf/
    - ../configs/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml

  hive-server2:
    image: hub.teko.vn/data/hive:3.1.2-hadoop-3.1.0
    entrypoint: ["/usr/local/scripts/hiveserver2-entrypoint.sh"]
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 10000:10000
    - 10002:10002 # WebUI
    volumes:
    - ./scripts/:/usr/local/scripts/
    - ../configs/hive/:/opt/hive/conf/
    - ../configs/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml

volumes:
  postgres_data:

networks:
  default:
    external:
      name: bookshelf
