services:
  jupyter:
    image: hub.teko.vn/dataops/jupyter/pyspark-notebook:3.4.1
    command: [start-notebook.sh, --NotebookApp.token='']
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    user: root
    ports:
    - 8888:8888
    - 4040:4040     # spark app
    volumes:
    - ../workspace:/home/jovyan/work
    - ./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

networks:
  default:
    name: bookshelf
