version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/dataops/pyspark-notebook:3.0.0
    command: [start-notebook.sh, --NotebookApp.token='']
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    ports:
    - 8888:8888
    - 4040:4040     # spark app
    volumes:
    - ../workspace:/home/jovyan/work

  statsd-exporter:
    image: prom/statsd-exporter:v0.13.0
    ports:
    - 9102:9102     # web
    - 9125:9125/tcp
    - 9125:9125/udp

  prom-pushgateway:
    image: prom/pushgateway:v1.0.1
    ports:
    - 9091:9091

networks:
  default:
    external:
      name: bookshelf
