version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/data/pyspark-notebook:2.4.4-hadoop-3.1.3
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    ports:
    - "8888:8888"
    volumes:
    - ./work:/home/jovyan/work

  statsd:
    image: prom/statsd-exporter:v0.13.0
    ports:
    - 9102:9102
    - 9125:9125/udp
