version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/dataops/pyspark-notebook:3.0.0
    command: [start-notebook.sh, --NotebookApp.token='']
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    user: root
    ports:
    - 8888:8888
    - 4040:4040     # spark app
    volumes:
    - ../workspace:/home/jovyan/work

networks:
  default:
    external:
      name: bookshelf
