version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/data/pyspark-notebook:2.4.4-hadoop-3.1.3
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    ports:
    - "8888:8888"
    volumes:
    - ./work:/home/jovyan/work
