version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/data/pyspark-notebook:2.4.4-hadoop-3.2.1
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    ports:
    - 8888:8888
    - 4040:4040     # spark app
    volumes:
    - ./work:/home/jovyan/work

  statsd-exporter:
    image: prom/statsd-exporter:v0.13.0
    ports:
    - 9102:9102     # web
    - 9125:9125/tcp
    - 9125:9125/udp

  prom-pushgateway:
    image: prom/pushgateway:v1.0.1
    ports:
    - 9091:9091
