# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository ppa:nginx/stable
    sudo apt-get update
    sudo apt-get install -y nginx
  SHELL
end
