services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4-alpine
    ports:
    - 8123:8123  # HTTP interface
    - 9000:9000  # native TCP interface
    volumes:
    - ./sample/:/docker-entrypoint-initdb.d/
    - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile: 262144

volumes:
  clickhouse_data:

networks:
  default:
    name: bookshelf
