services:
  redis:
    image: redis:7.0-alpine
    # ports:
    # - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  engine:
    image: grafana/oncall:v1.1.14
    command: [uwsgi, --ini=uwsgi.ini]
    env_file: [oncall.env]
    ports:
      - 8080:8080
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully

  celery:
    image: grafana/oncall:v1.1.14
    command: [./celery_with_exporter.sh]
    env_file: [oncall.env]
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully

  db_migration:
    image: grafana/oncall:v1.1.14
    command: [python, manage.py, migrate, --noinput]
    env_file: [oncall.env]
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy

volumes:
  oncall_data:

networks:
  default:
    name: bookshelf
