x-common: &common
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Ho_Chi_Minh
    dns:
      - 1.1.1.1
      - 1.0.0.1

# https://wiki.servarr.com/
# https://github.com/automation-avenue/arr-new/blob/main/docker-compose.yml
services:
  ###############################################
  # RADARR - Movies
  ###############################################
  radarr:
    <<: *common
    image: lscr.io/linuxserver/radarr:6.1.1
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads

  ###############################################
  # QBITTORRENT - Downloader
  ###############################################
  qbittorrent:
    <<: *common
    image: lscr.io/linuxserver/qbittorrent:5.2.0
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads

  ###############################################
  # JELLYFIN - Media Server
  ###############################################
  jellyfin:
    <<: *common
    image: lscr.io/linuxserver/jellyfin:10.11.8
    container_name: jellyfin
    environment:
      DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ./data/downloads:/data
      # Using OCI image: https://github.com/moby/moby/pull/48798
      # - type: image
      #   source: lscr.io/linuxserver/mods:jellyfin-opencl-intel
      #   target: /foobar
      #   read_only: true
    ports:
      - 8096:8096 # HTTP WebUI

volumes:
  jellyfin_config:
  jellyfin_cache:
