x-common: &common
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Ho_Chi_Minh
    dns:
      - 1.1.1.1
      - 1.0.0.1

# https://wiki.servarr.com/
# https://trash-guides.info/
# https://locatarr.github.io/
# https://lavx.github.io/arrstack/
# https://github.com/automation-avenue/arr-new/blob/main/docker-compose.yml
# https://youtu.be/ho4NUoyU6tM
services:
  ###############################################
  # RADARR - Movies
  ###############################################
  radarr:
    <<: *common
    image: lscr.io/linuxserver/radarr:6.1.1
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - media_data:/data

  ###############################################
  # SONARR - TV Shows
  ###############################################
  sonarr:
    <<: *common
    image: lscr.io/linuxserver/sonarr:4.0.17
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - sonarr_config:/config
      - media_data:/data

  ###############################################
  # WHISPARR - X Videos
  ###############################################
  # whisparr:
  #   <<: *common
  #   image: ghcr.io/hotio/whisparr:v3
  #   container_name: whisparr
  #   environment:
  #     - WEBUI_PORTS=6969/tcp
  #   ports:
  #     - "6969:6969"
  #   volumes:
  #     - whisparr_config:/config
  #     - media_data:/data

  ###############################################
  # LIDARR - Music
  ###############################################
  lidarr:
    <<: *common
    image: lscr.io/linuxserver/lidarr:3.1.0
    container_name: lidarr
    ports:
      - 8686:8686
    volumes:
      - lidarr_config:/config
      - media_data:/data

  ###############################################
  # PROWLARR - Index Manager
  ###############################################
  prowlarr:
    <<: *common
    image: lscr.io/linuxserver/prowlarr:2.3.5
    container_name: prowlarr
    ports:
      - 9696:9696
    volumes:
      - prowlarr_config:/config

  ###############################################
  # BAZARR - Subtitles
  # Bazarr+: Enhanced subtitle management w/ AI translation
  ###############################################
  bazarr:
    <<: *common
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media

  ###############################################
  # SEERR - Media request and discovery manager
  ###############################################
  seerr:
    <<: *common
    image: ghcr.io/seerr-team/seerr:v3.2
    container_name: seerr
    init: true
    ports:
      - 5055:5055
    volumes:
      - seerr_config:/app/config

  ###############################################
  # QBITTORRENT - Downloader
  ###############################################
  qbittorrent:
    <<: *common
    image: lscr.io/linuxserver/qbittorrent:5.2.0
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads

  ###############################################
  # JELLYFIN - Media Server
  ###############################################
  jellyfin:
    <<: *common
    image: lscr.io/linuxserver/jellyfin:10.11.8
    container_name: jellyfin
    environment:
      # Sideload DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel
      DOCKER_MODS: jellyfin-opencl-intel
      DOCKER_MODS_SIDELOAD: true
      DOCKER_MODS_DEBUG: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - media_data:/data
      # Using OCI image: https://github.com/moby/moby/pull/48798
      - type: image
        source: lscr.io/linuxserver/mods:jellyfin-opencl-intel
        target: /mods/jellyfin-opencl-intel
    ports:
      - 8096:8096 # HTTP WebUI

volumes:
  media_data:
  radarr_config:
  sonarr_config:
  # whisparr_config:
  lidarr_config:
  prowlarr_config:
  seerr_config:
  jellyfin_config:
  jellyfin_cache:
