# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    wget -qO - https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
    echo "deb https://packages.fluentbit.io/ubuntu/bionic bionic main" > /etc/apt/sources.list.d/fluentbit.list

    apt update
    apt install td-agent-bit

    ln -s /opt/td-agent-bit/bin/td-agent-bit /usr/local/bin/fluent-bit
  SHELL
end
