services:
  debezium:
    image: quay.io/debezium/connect:3.5.0.Final
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: debezium
      CONFIG_STORAGE_TOPIC: debezium.configs
      OFFSET_STORAGE_TOPIC: debezium.offsets
      STATUS_STORAGE_TOPIC: debezium.statuses
    ports:
    - 8083:8083

  debezium-ui:
    image: quay.io/debezium/debezium-ui:2.5
    profiles: [ ui ]
    depends_on:
    - debezium
    environment:
      KAFKA_CONNECT_URI: http://debezium:8083
    ports:
    - 8080:8080

networks:
  default:
    name: bookshelf
