version: '2'

services:
  zookeeper:
    image: debezium/zookeeper:1.0
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

  kafka:
    image: debezium/kafka:1.0
    ports:
    - 9092:9092
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
