version: '2'

services:
  zookeeper:
    image: debezium/zookeeper:1.0
    ports:
    - 2181:2181 # client connections
    - 2888:2888 # peers connections
    - 3888:3888 # leader election

  kafka:
    image: debezium/kafka:1.0
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper
    ports:
    - 9092:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    depends_on:
    - zookeeper
    - kafka
    ports:
    - 8081:8081

  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ../../database/sample/mysql/:/docker-entrypoint-initdb.d/
    - ./mysql/user-debezium.sql:/docker-entrypoint-initdb.d/user-debezium.sql
    - mysql_data:/var/lib/mysql

  debezium:
    image: debezium/connect:1.0
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium.configs
      OFFSET_STORAGE_TOPIC: debezium.offsets
      STATUS_STORAGE_TOPIC: debezium.statuses
    depends_on:
    - kafka
    ports:
    - 8083:8083

volumes:
  mysql_data:
