kafka:
  brokers:
    - kafka:9092

schemaRegistry:
  enabled: true
  urls:
    - http://schema-registry:8081

kafkaConnect:
  enabled: true
  clusters:
    - name: datagen
      url: http://datagen:8083
