# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-8-jdk

    # Install Jenkins
    # ref: https://jenkins.io/download/
    # ref: https://linuxize.com/post/how-to-install-jenkins-on-ubuntu-18-04/
    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
    echo 'deb http://pkg.jenkins.io/debian-stable binary/' > /etc/apt/sources.list.d/jenkins.list
    apt-get update
    apt-get install -y jenkins
  SHELL
end
