version: '3.7'

services:
  tempo:
    image: grafana/tempo:2.1.1
    command:
    - --config.file=/etc/tempo/tempo.yml
    ports:
    - 4317:4317     # OTLP/gRPC
    - 4318:4318     # OTLP/HTTP
    - 14250:14250   # Jaeger/gRPC
    - 14268:14268   # Jaeger/Thrift HTTP
    - 6832:6832/udp # Jaeger/Thrift Binary
    - 6831:6831/udp # Jaeger/Thrift Compact
    - 9411:9411     # Zipkin
    - 55678:55678   # OpenCensus
    volumes:
    - ./configs:/etc/tempo
    - tempo_data:/var/lib/tempo

volumes:
  tempo_data:

networks:
  default:
    name: bookshelf
    external: true
