services:
  ##### MySQL #####
  # https://hub.docker.com/_/mysql
  # Help:
  # > mysql -u root -p
  mysql:
    image: mysql:8.0
    command:
    - --default-authentication-plugin=mysql_native_password
    # - --performance-schema-instrument=statement/%=ON
    # - --performance-schema-consumer-statements-digest=ON
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ./sample/:/docker-entrypoint-initdb.d/
    - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    name: bookshelf
