version: '3'

services:
  database:
      image: postgres:9.6-alpine
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      volumes:
      - database_data:/var/lib/postgresql/data

  keycloak:
      image: jboss/keycloak:6.0.0
      environment:
        DB_VENDOR: postgres
        DB_ADDR: database
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password

        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: SuperSecr3t
      ports:
      - 8080:8080
      depends_on:
      - database

volumes:
  database_data:
    driver: local
