version: '3'

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB:        keycloak
      POSTGRES_USER:      keycloak
      POSTGRES_PASSWORD:  password
    volumes:
    - database_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:11.0.0
    environment:
      DB_VENDOR:    postgres
      DB_ADDR:      database
      DB_DATABASE:  keycloak
      DB_USER:      keycloak
      DB_PASSWORD:  password

      KEYCLOAK_USER:      admin
      KEYCLOAK_PASSWORD:  SuperSecr3t
    ports:
    - 8080:8080
    depends_on:
    - database

volumes:
  database_data:
    driver: local

networks:
  default:
    external:
      name: bookshelf

##### References #####
# https://www.keycloak.org/2019/05/keycloak-cluster-setup.html
