# -*- mode: ruby -*-
# vi: set ft=ruby :

keycloak_version = "6.0.0"
keycloak_download_url = "https://downloads.jboss.org/keycloak/#{keycloak_version}/keycloak-#{keycloak_version}.tar.gz"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
    apt-get install -y openjdk-8-jre

    if [ ! -d /opt/jboss/keycloak ]; then
      mkdir -p /opt/jboss/
      curl -L #{keycloak_download_url} -o keycloak.tar.gz
      tar -xzvf keycloak.tar.gz
      mv keycloak-?.?.?* /opt/jboss/keycloak
      rm keycloak.tar.gz
    fi
  SHELL
end
