# Prometheus is configured via command-line flags and a configuration file.
# While the command-line flags configure immutable system parameters
# (such as storage locations, amount of data to keep on disk and in memory, etc.),
# the configuration file defines everything related to scraping jobs
# and their instances, as well as which rule files to load.
