[[servers]]
host = "10.148.0.17"
port = 10389
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "uid=admin,ou=system"
bind_password = 'secret'

search_filter = "(|(uid=%s)(email=%s))"
#search_base_dns = ["dc=example,dc=com"] # for specific domain
search_base_dns = [""]  # for all domains

[servers.attributes]
name = "cn"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "email"
