version: "3.7"

services:
  presto:
    image: prestosql/presto:332
    ports:
    - 8080:8080
    volumes:
    - ./catalog:/etc/presto/catalog
    - ../configs/presto:/etc/presto

networks:
  default:
    external:
      name: bookshelf
