version: "3.7"

services:
  presto:
    image: prestosql/presto:338
    ports:
    - 8080:8080
    - 9000:9000
    volumes:
    - ./catalog:/etc/presto/catalog
    - ./utils:/usr/lib/presto/utils
    - ../configs/presto:/etc/presto

networks:
  default:
    external:
      name: bookshelf
