# -*- mode: ruby -*-
# vi: set ft=ruby :

presto_version = '327'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    apt-get update
    apt-get install -y curl apt-transport-https openjdk-8-jdk
    ln -sf /usr/bin/python3 /usr/bin/python

    if [ -d "/opt/presto" ]; then
      exit 0;
    fi

    cd /opt
    curl -LO  https://repo1.maven.org/maven2/io/prestosql/presto-server/#{presto_version}/presto-server-#{presto_version}.tar.gz
    tar -xzvf presto-server-#{presto_version}.tar.gz
    mv        presto-server-#{presto_version} presto

    cd presto
    mkdir etc data
    # https://prestodb.io/docs/current/installation/deployment.html#configuring-presto
    cp -r /vagrant/configs/presto/* /opt/presto/etc/

    cp /vagrant/presto.service /lib/systemd/system/
    systemctl daemon-reload
    systemctl enable presto
    systemctl start  presto
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    if command -v presto; then
      exit 0;
    fi

    curl -LO https://repo1.maven.org/maven2/io/prestosql/presto-cli/#{presto_version}/presto-cli-#{presto_version}-executable.jar
    chmod +x presto-cli-#{presto_version}-executable.jar
    mv       presto-cli-#{presto_version}-executable.jar /usr/local/bin/presto
  SHELL
end
