version: "3.7"

services:
  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ../../../database/sample/mysql/:/docker-entrypoint-initdb.d/
    - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    ports:
    - 5432:5432
    volumes:
    - ../../../database/sample/postgres/:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  sdc:
    # The default login is: admin / admin.
    image: streamsets/datacollector:3.13.0
    ports:
    - 18630:18630

volumes:
  mysql_data:
  postgres_data:


##### References
# https://github.com/streamsets/datacollector-docker
# https://github.com/streamsets/tutorials
