services:
  # https://garagehq.deuxfleurs.fr/documentation/quick-start/
  garage:
    image: dxflrs/garage:v2.2.0
    ports:
      - 3900:3900  # S3 API
      - 3901:3901  # RPC
      - 3902:3902  # S3 Web
      - 3903:3903  # Admin API
    volumes:
      - ./garage.toml:/etc/garage.toml:ro

  # https://github.com/khairul169/garage-webui
  garage-webui:
    image: khairul169/garage-webui:1.1.0
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

networks:
  default:
    name: bookshelf
