metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "cd35cb53375de694cf18b2e4aba58c1f0b171825724db4e5196704e387946b0a"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "z21wzIh5g4nO0kudtzl0frs2UkASvonmfC50T8eDKIQ="
metrics_token = "N1l/OcwnqiyCcv2gDk9TBI6yXDGXpYDe2CAmn+0yPL0="
