# -*- mode: ruby -*-
# vi: set ft=ruby :

graalvm_version = "19.0.0"
graalvm_download_url = "https://github.com/oracle/graal/releases/download/vm-#{graalvm_version}/graalvm-ce-linux-amd64-#{graalvm_version}.tar.gz"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl

    if [ ! -d /opt/graalvm-ce ]; then
      curl -L #{graalvm_download_url} -o graalvm-ce.tar.gz
      tar  -xzvf graalvm-ce.tar.gz -C /opt/
      mv   /opt/graalvm-ce-19.0.0 /opt/graalvm-ce
      rm   graalvm-ce.tar.gz
    fi
  SHELL
end
