services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.40.7
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus/
    - --web.enable-remote-write-receiver # the remote write receiver endpoint is /api/v1/write
    ports:
    - 9090:9090
    volumes:
    - ./configs:/etc/prometheus
    - prometheus_data:/prometheus

  alertmanager:
    profiles: [alertmanager]
    image: quay.io/prometheus/alertmanager:v0.24.0
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    ports:
    - 9093:9093
    volumes:
    - alertmanager_data:/alertmanager

volumes:
  prometheus_data:
  alertmanager_data:

networks:
  default:
    name: bookshelf
