version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: false
      BADGER_DIRECTORY_KEY: /var/lib/jaeger/key
      BADGER_DIRECTORY_VALUE: /var/lib/jaeger/value
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
    - 5775:5775/udp # Zipkin/Thrift compact (deprecated)
    - 6831:6831/udp # Jaeger/Thrift compact
    - 6832:6832/udp # Jaeger/Thrift binary

    - 5778:5778     # serve configs (sampling, etc.)
    - 16685:16685   # gRPC QueryService
    - 16686:16686   # Jaeger UI
    - 14269:14269   # Admin port: health check at / and metrics at /metrics
    - 14268:14268   # accept jaeger.thrift directly from clients
    - 14250:14250   # accept model.proto

    - 4317:4317     # OTLP/gRPC
    - 4318:4318     # OTLP/HTTP
    - 9411:9411     # Zipkin (Thrift, JSON and Proto)
    volumes:
    - jaeger_data:/var/lib/jaeger

volumes:
  jaeger_data:

networks:
  default:
    name: bookshelf
    external: true
