version: '3.7'

services:
  agent:
    image: grafana/agent:v0.27.1
    command:
    - -config.file=/etc/agent/agent.yaml
    volumes:
    - ./configs:/etc/agent
    - agent_data:/var/lib/agent/

  avalanche:
    profiles: [example]
    image: quay.io/freshtracks.io/avalanche:latest
    command:
    - --metric-count=3000
    - --series-interval=3600
    - --metric-interval=7200
    ports:
    - 9001:9001

volumes:
  agent_data:

networks:
  default:
    name: bookshelf
    external: true
