version: '3.7'

services:
  loki:
    image: grafana/loki:2.6.1
    command:
    - -config.file=/etc/loki/local-config.yaml
    ports:
    - 3100:3100
    # volumes:
    # - ./configs/loki:/etc/loki

networks:
  default:
    name: bookshelf
    external: true
