# -*- mode: ruby -*-
# vi: set ft=ruby :

version = "v1.4.0"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y curl unzip
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    curl -LO "https://github.com/grafana/loki/releases/download/#{version}/loki-linux-amd64.zip"

    unzip    "loki-linux-amd64.zip"
    chmod +x "loki-linux-amd64"
    mv       "loki-linux-amd64" "/usr/local/bin/loki"
    rm -rf   "loki-linux-amd64.zip"
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    curl -LO "https://github.com/grafana/loki/releases/download/#{version}/logcli-linux-arm64.zip"

    unzip    "logcli-linux-arm64.zip"
    chmod +x "logcli-linux-arm64"
    mv       "logcli-linux-arm64" "/usr/local/bin/logcli"
    rm -rf   "logcli-linux-arm64.zip"
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    curl -LO "https://github.com/grafana/loki/releases/download/#{version}/promtail-linux-amd64.zip"

    unzip    "promtail-linux-amd64.zip"
    chmod +x "promtail-linux-amd64"
    mv       "promtail-linux-amd64" "/usr/local/bin/promtail"
    rm -rf   "promtail-linux-amd64.zip"
  SHELL
end
