services:
  nexus:
    image: sonatype/nexus3:3.65.0
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: "false"
    ports:
    - "8081:8081"
    # network_mode: host
    volumes:
    - ./configs/admin.password:/nexus-data/admin.password
    - nexus-data:/nexus-data

volumes:
  nexus-data:
